/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intercalacion;

import Funciones.Llave;
import Funciones.LecturaDeArchivo;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.io.RandomAccessFile;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author yaser
 */
public class Intercalacion extends javax.swing.JFrame {

    public String Archivo1 = "";
    public String Archivo2 = "";
    RandomAccessFile file;
    /**
     * Creates new form Intercalacion
     */
    public Intercalacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArchivo1 = new javax.swing.JLabel();
        lblArchivo2 = new javax.swing.JLabel();
        txtArchivo1 = new javax.swing.JTextField();
        TxtArchivo2 = new javax.swing.JTextField();
        btnArchivo1 = new javax.swing.JButton();
        btnAchivo2 = new javax.swing.JButton();
        BtnIntercalacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Intercalación");

        lblArchivo1.setText("Archivo 1");

        lblArchivo2.setText("Archivo 2");

        btnArchivo1.setText("Buscar Archivo 1");
        btnArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivo1ActionPerformed(evt);
            }
        });

        btnAchivo2.setText("Buscar Archivo 2");
        btnAchivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAchivo2ActionPerformed(evt);
            }
        });

        BtnIntercalacion.setText("Intercalaciön");
        BtnIntercalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIntercalacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtArchivo1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(TxtArchivo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnArchivo1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(btnAchivo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(BtnIntercalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArchivo1))
                .addGap(18, 18, 18)
                .addComponent(lblArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAchivo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(BtnIntercalacion)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivo1ActionPerformed
        // TODO add your handling code here:
        //estoy creano mi vairable archivo de la clase jfilechooser, con el constructor vacio
        JFileChooser archivo = new JFileChooser();
        archivo.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //filtro para permitir que solo acepte los archivos txt
        FileNameExtensionFilter txtfile = new FileNameExtensionFilter("Archivos de Texto plano .txt", "txt");

        //asigne el filtro al selector de archivos
        archivo.setFileFilter(txtfile);

        //el this hace referencia a esta misma clase
        int resultado = archivo.showOpenDialog(this);

        //aqui hacemos la comparacion 
        if (resultado != JFileChooser.CANCEL_OPTION) {
            File file = archivo.getSelectedFile();
            txtArchivo1.setText(file.getAbsolutePath());
            if (file == null || (file.getName().equals(""))) {
                JOptionPane.showMessageDialog(rootPane, "La carga del archivo fue cancelada",
                        "uups! algo malio sal",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {

            JOptionPane.showMessageDialog(rootPane, "La carga del archivo fue cancelada",
                    "uups! algo malio sal",
                    JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnArchivo1ActionPerformed

    private void btnAchivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAchivo2ActionPerformed
        // TODO add your handling code here:
        //estoy creano mi vairable archivo de la clase jfilechooser, con el constructor vacio
        JFileChooser archivo = new JFileChooser();
        archivo.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //filtro para permitir que solo acepte los archivos txt
        FileNameExtensionFilter txtfile = new FileNameExtensionFilter("Archivos de Texto plano .txt", "txt");

        //asigne el filtro al selector de archivos
        archivo.setFileFilter(txtfile);

        //el this hace referencia a esta misma clase
        int resultado = archivo.showOpenDialog(this);

        //aqui hacemos la comparacion 
        if (resultado != JFileChooser.CANCEL_OPTION) {
            File file = archivo.getSelectedFile();
            TxtArchivo2.setText(file.getAbsolutePath());
            if (file == null || (file.getName().equals(""))) {
                JOptionPane.showMessageDialog(rootPane, "La carga del archivo fue cancelada",
                        "uups! algo malio sal",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {

            JOptionPane.showMessageDialog(rootPane, "La carga del archivo fue cancelada",
                    "uups! algo malio sal",
                    JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnAchivo2ActionPerformed

    private void BtnIntercalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIntercalacionActionPerformed
        // TODO add your handling code here:
        //Creamos una instancia de la clase para acceder a sus metodos
        Archivo1=txtArchivo1.getText().trim();
        if(Archivo1.isEmpty()){
            JOptionPane.showMessageDialog(this, "el campo de archivo 1 esta vacio, favor de rellenarlo","error",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Archivo2=TxtArchivo2.getText().trim();
        if(Archivo2.isEmpty()){
            JOptionPane.showMessageDialog(this, "el campo de archivo 2 esta vacio, favor de rellenarlo","error",JOptionPane.WARNING_MESSAGE);
            return;
        }
        LecturaDeArchivo lectu = new LecturaDeArchivo();

        lectu.escribirTxtDat(this.Archivo1, "llaves.dat");
        lectu.escribirTxtDat(this.Archivo2, "llaves.dat");

        int llave1 = 0;
   
        try {
            RandomAccessFile file1 = new RandomAccessFile("llaves.dat", "rw");
            //Creamos un objetos de persona
            Llave p1 = new Llave();
            //Creamos dos arreglos para compararlos posteriormente
            int[] arr1 = new int[80];
            //Llenamos arr1
            int contador = 0;
            while(file1.getFilePointer()<file1.length()){
                p1.leer(file1);
                llave1 = p1.getLlave();
                arr1[contador] = llave1;
                contador++;
            }
            Arrays.sort(arr1);
            for(int f = 0; f < arr1.length; f ++){
                lectu.escribirDat("llavesOrdenadas.dat", arr1[f]);
            }
            lectu.reporte("llavesOrdenadas.dat");
            
            file1.close();
        } catch (Exception e) {
            System.out.println("Ha ocurrido un error: " + e);
        }
    }//GEN-LAST:event_BtnIntercalacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intercalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intercalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intercalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intercalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intercalacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIntercalacion;
    private javax.swing.JTextField TxtArchivo2;
    private javax.swing.JButton btnAchivo2;
    private javax.swing.JButton btnArchivo1;
    private javax.swing.JLabel lblArchivo1;
    private javax.swing.JLabel lblArchivo2;
    private javax.swing.JTextField txtArchivo1;
    // End of variables declaration//GEN-END:variables
}
